# This is a basic workflow to help you get started with Actions

name: Create new bundle

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      BASE_URL: "https://api.segmentapis.com"
      TAXONOMY_CORE_ID: "tp_1wp3VoPyrRCNbl3lJT6PDUCi5rN"
      TAXONOMY_UPDATES_ID: "tp_1ybAXDkFHogu5SarT9gozVQYu6j"
      JSON_RULES_ID: "sfnc_hxdpUMFSYO"
      LOOKUP_RULES_ID: "sfnc_TNhNLzGwpl"
      CODE_BASE_ID: ""
      CORE_INGESTION_FUNTCION_ID: ""
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Initialize env variables
        run: |
          TAXONOMY_CORE=$(cat ./src/assets/taxonomy_core.json)
          TAXONOMY_UPDATES=$(cat ./src/assets/taxonomy_updates.json)
          JSON_RULES=$(cat ./src/assets/json_rules.json | jq '.data.function.code')
          LOOKUP_RULES=$(cat ./src/assets/lookup_rules.json | jq '.data.function.code')
          echo $JSON_RULES
