# This is a basic workflow to help you get started with Actions

name: Pull assets

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      
      - name: Fetch taxonomy
        run: |
          TRACKING_PLAN=$(curl --location --request GET --header "Authorization: Bearer dycTCNXIQV1OmpEkmOF0otbCet9H7Y-iB8Zsm7NmdVc.bhGWwdvwotC_Va6l3Lg-aNXWtPhFKaRsQnHfygb0WF4" --url "https://platform.segmentapis.com/v1beta/workspaces/wawa-dev/tracking-plans/rs_1tAx8iqnqw9Whin7DLQXqjCh04n")
          echo $TRACKING_PLAN >> taxonomy.json 
          mkdir -p output
          yes| cp -rf taxonomy.json ./output/
      
      - name: Diff report
        run:
          git diff origin/main -- ./output/
          
      - name: Commit/Push files in the output folder
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./output
          git commit -m "Update detected"
          git push
